// ignore_for_file: no_leading_underscores_for_local_identifiers, unused_local_variable

import 'dart:io';
import 'package:dental_pt/features/Patient%20registration/domain/entities/diagnosis.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:dental_pt/features/Patient%20registration/domain/entities/patient.dart';
import '../bloc/patient_registration_bloc.dart';
import '../widgets/widgets.dart';
import '../widgets/image_picker_widget.dart';

class HomeDoctorPage extends StatelessWidget {
  HomeDoctorPage({super.key});

  // Moved _diagnoses to be a class-level variable
  final List<DiagnosisEntry> _diagnoses = [DiagnosisEntry()];

  void _handleAddPatient(
    BuildContext context,
    TextEditingController nameController,
    TextEditingController phoneController,
    TextEditingController ageController,
    String selectedType,
    String selectedGender,
    GlobalKey<FormState> formKey,
    File? nationalIdFaceImage,
    File? nationalIdBackImage,
  ) {
    if (formKey.currentState!.validate()) {
      // Ensure all fields are validated before submission
      final patient = Patient(
        name: nameController.text.trim(),
        age: int.parse(ageController.text),
        phone: int.parse(phoneController.text),
        gander: selectedGender,
        id: 0, // Will be generated by backend
        nationalIdFaceUrl: null,
        nationalIdBackUrl: null,
        diagnoses: _diagnoses.map((entry) {
          if (entry.diagnosis.value.isEmpty ||
              entry.quadrant.value.isEmpty ||
              entry.toothNumber.value.isEmpty ||
              entry.additionalInfo.text.trim().isEmpty) {
            throw Exception('All diagnosis fields are required.');
          }
          return Diagnosis(
            id: 0, // Will be generated by backend
            name: entry.diagnosis.value,
            description: entry.additionalInfo.text.trim(),
            noOfTooth: entry.noOfTooth, // Combine quadrant and tooth number
          );
        }).toList(),
      );

      context.read<PatientRegistrationBloc>().add(
            RegisterPatientEvent(
              patient: patient,
              nationalIdFaceImage: nationalIdFaceImage,
              nationalIdBackImage: nationalIdBackImage,
            ),
          );
    }
  }

  @override
  Widget build(BuildContext context) {
    final _formKey = GlobalKey<FormState>();
    final _nameController = TextEditingController();
    final _phoneController = TextEditingController();
    final _ageController = TextEditingController();
    final _selectedType = ValueNotifier<String>('General');
    final _selectedGender = ValueNotifier<String>('Male');

    // Image state
    File? _nationalIdFaceImage;
    File? _nationalIdBackImage;
    int? _registeredPatientId;

    Widget _buildDiagnosisSection(BuildContext context, DiagnosisEntry entry) {
      return Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Diagnosis Dropdown
          DiagnosisDropdown(
            diagnosisNotifier: entry.diagnosis,
          ),
          const SizedBox(height: 16),

          // Quadrant and Tooth Number Box
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              border: Border.all(color: const Color(0xFF065091).withOpacity(0.3)),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Quadrant Dropdown
                DropdownButtonFormField<String>(
                  initialValue: entry.quadrant.value,
                  items: ['LL', 'UL', 'LR', 'UR']
                      .map((q) => DropdownMenuItem(value: q, child: Text(q)))
                      .toList(),
                  onChanged: (value) {
                    if (value != null) entry.quadrant.value = value;
                  },
                  decoration: const InputDecoration(labelText: 'Quadrant'),
                ),
                const SizedBox(height: 16),

                // Tooth Number Dropdown
                DropdownButtonFormField<String>(
                  initialValue: entry.toothNumber.value,
                  items: List.generate(8, (index) => (index + 1).toString())
                      .map((num) =>
                          DropdownMenuItem(value: num, child: Text(num)))
                      .toList(),
                  onChanged: (value) {
                    if (value != null) entry.toothNumber.value = value;
                  },
                  decoration: const InputDecoration(labelText: 'Tooth Number'),
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),

          // Additional Info Field
          AdditionalInfoField(
            controller: entry.additionalInfo,
          ),
          const SizedBox(height: 16),
        ],
      );
    }

    return Scaffold(
      appBar: DoctorAppBar(
        doctorName: "back",
        onProfileTap: () {
          // Navigate to profile page
        },
      ),
      body: BlocConsumer<PatientRegistrationBloc, PatientRegistrationState>(
        listener: (context, state) {
          if (state is PatientRegistrationSuccess) {
            _registeredPatientId = state.patientId;

            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content:
                    Text('Patient added successfully with National ID images!'),
                backgroundColor: Color(0xFFee7733),
              ),
            );
            // Clear form
            _nameController.clear();
            _phoneController.clear();
            _ageController.clear();
            _selectedType.value = 'General';
            _selectedGender.value = 'Male';
            _nationalIdFaceImage = null;
            _nationalIdBackImage = null;
          } else if (state is PatientRegistrationFailure) {
            showDialog(
              context: context,
              builder: (BuildContext context) {
                return AlertDialog(
                  title: const Text('Error'),
                  content: SingleChildScrollView(
                    child: Text(state.error),
                  ),
                  actions: [
                    TextButton(
                      onPressed: () => Navigator.of(context).pop(),
                      child: const Text('Close'),
                    ),
                  ],
                );
              },
            );
          } else if (state is ImagePickedSuccess) {
            // Update image state based on type
            if (state.imageType == 'face') {
              _nationalIdFaceImage = state.image;
            } else if (state.imageType == 'back') {
              _nationalIdBackImage = state.image;
            }
            // Trigger rebuild
            (context as Element).markNeedsBuild();
          }
        },
        builder: (context, state) {
          final isLoading = state is PatientRegistrationLoading;

          return SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Header
                  Text(
                    'Add New Patient',
                    style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Fill in the patient details below',
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                          color: Color(0xFF065091).withOpacity(0.6),
                        ),
                  ),
                  const SizedBox(height: 32),

                  // Patient Name Field
                  PatientNameField(
                    controller: _nameController,
                    enabled: !isLoading,
                  ),
                  const SizedBox(height: 16),

                  // Phone Field
                  PatientPhoneField(
                    controller: _phoneController,
                    enabled: !isLoading,
                  ),
                  const SizedBox(height: 16),

                  // Age Field
                  PatientAgeField(
                    controller: _ageController,
                    enabled: !isLoading,
                  ),
                  const SizedBox(height: 16),

                  // Gender Dropdown
                  PatientGenderDropdown(
                    genderNotifier: _selectedGender,
                    enabled: isLoading,
                  ),
                  const SizedBox(height: 32),

                  // National ID Images Section
                  Text(
                    'National ID Images',
                    style: Theme.of(context).textTheme.titleLarge?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                  ),
                  const SizedBox(height: 16),

                  // National ID Face Image
                  ImagePickerWidget(
                    label: 'National ID (Front)',
                    image: _nationalIdFaceImage,
                    onPickImage: () {
                      context.read<PatientRegistrationBloc>().add(
                            const PickImageEvent(imageType: 'face'),
                          );
                    },
                    enabled: !isLoading,
                  ),
                  const SizedBox(height: 16),

                  // National ID Back Image
                  ImagePickerWidget(
                    label: 'National ID (Back)',
                    image: _nationalIdBackImage,
                    onPickImage: () {
                      context.read<PatientRegistrationBloc>().add(
                            const PickImageEvent(imageType: 'back'),
                          );
                    },
                    enabled: !isLoading,
                  ),
                  const SizedBox(height: 32),

                  // Diagnosis Section
                  ..._diagnoses
                      .map((entry) => _buildDiagnosisSection(context, entry)),

                  // Add Another Diagnosis Button
                  TextButton.icon(
                    onPressed: () {
                      _diagnoses.add(DiagnosisEntry());
                      (context as Element)
                          .markNeedsBuild(); // Trigger UI rebuild
                    },
                    icon: const Icon(Icons.add),
                    label: const Text('Add Another Diagnosis'),
                  ),
                  const SizedBox(height: 32),

                  // Submit Button
                  AddPatientSubmitButton(
                    onPressed: () => _handleAddPatient(
                      context,
                      _nameController,
                      _phoneController,
                      _ageController,
                      _selectedType.value,
                      _selectedGender.value,
                      _formKey,
                      _nationalIdFaceImage,
                      _nationalIdBackImage,
                    ),
                    isLoading: isLoading,
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}

class DiagnosisEntry {
  final ValueNotifier<String> diagnosis;
  final ValueNotifier<String> quadrant;
  final ValueNotifier<String> toothNumber;
  final TextEditingController additionalInfo;

  DiagnosisEntry()
      : diagnosis = ValueNotifier<String>('Diagnosis 1'),
        quadrant = ValueNotifier<String>('LL'),
        toothNumber = ValueNotifier<String>('1'),
        additionalInfo = TextEditingController();

  String get noOfTooth => "${quadrant.value}-${toothNumber.value}";
}

