// ignore_for_file: no_leading_underscores_for_local_identifiers

import 'package:dental_pt/core/routes/routes_name.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:dental_pt/features/Auth/domain/entities/user.dart';
import '../bloc/auth_bloc.dart';
import '../widgets/widgets.dart';

class SignUpPage extends StatelessWidget {
  const SignUpPage({super.key});

  void _handleSignUp(
    BuildContext context,
    TextEditingController nameController,
    TextEditingController emailController,
    TextEditingController passwordController,
    TextEditingController confirmPasswordController,
    TextEditingController phoneController,
    TextEditingController ageController,
    String selectedRole,
    GlobalKey<FormState> formKey,
  ) {
    if (formKey.currentState!.validate()) {
      if (passwordController.text != confirmPasswordController.text) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Passwords do not match!'),
            backgroundColor: Color(0xFFd32f2f),
          ),
        );
        return;
      }

      final user = User(
        id: 0, // Placeholder - will be auto-generated by database
        name: nameController.text.trim(),
        email: emailController.text.trim(),
        password: passwordController.text,
        role: selectedRole,
        phone: int.parse(phoneController.text),
        age: int.parse(ageController.text),
      );

      context.read<AuthBloc>().add(SignUpEvent(user: user));
    }
  }

  @override
  Widget build(BuildContext context) {
    final _formKey = GlobalKey<FormState>();
    final _nameController = TextEditingController();
    final _emailController = TextEditingController();
    final _passwordController = TextEditingController();
    final _confirmPasswordController = TextEditingController();
    final _phoneController = TextEditingController();
    final _ageController = TextEditingController();
    final _selectedRole = ValueNotifier<String>('Patient');

    return Scaffold(
      body: SafeArea(
        child: BlocConsumer<AuthBloc, AuthState>(
          listener: (context, state) {
            if (state is AuthFailure) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text(state.error),
                  backgroundColor: Colors.red.shade700,
                ),
              );
            } else if (state is AuthSignUpSuccess) {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Account created successfully!'),
                  backgroundColor: Color(0xFFee7733),
                ),
              );
              // Navigate to login or home
              Navigator.pushReplacementNamed(context, RoutesName.login);
            }
          },
          builder: (context, state) {
            final isLoading = state is AuthLoading;

            return Center(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(24.0),
                child: Form(
                  key: _formKey,
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      // Logo or App Icon
                    

                      // App Title and Subtitle
                      const AuthHeader(
                        title: 'Dental Pt.',
                        subtitle: 'Create your account to get started',
                      ),
                      const SizedBox(height: 32),

                      // Full Name Field
                      NameField(
                        controller: _nameController,
                        enabled: !isLoading,
                      ),
                      const SizedBox(height: 16),

                      // Email Field
                      EmailField(
                        controller: _emailController,
                        enabled: !isLoading,
                      ),
                      const SizedBox(height: 16),

                      // Phone Field
                      PhoneField(
                        controller: _phoneController,
                        enabled: !isLoading,
                      ),
                      const SizedBox(height: 16),

                      // Age Field
                      AgeField(
                        controller: _ageController,
                        enabled: !isLoading,
                      ),
                      const SizedBox(height: 16),

                      // Role Dropdown
                      RoleDropdown(
                        onRoleChanged: (role) {
                          _selectedRole.value = role;
                        },
                        enabled: !isLoading,
                      ),
                      const SizedBox(height: 16),

                      // Password Field
                      PasswordField(
                        controller: _passwordController,
                        label: 'Password',
                        enabled: !isLoading,
                      ),
                      const SizedBox(height: 16),

                      // Confirm Password Field
                      PasswordField(
                        controller: _confirmPasswordController,
                        label: 'Confirm Password',
                        enabled: !isLoading,
                      ),
                      const SizedBox(height: 24),

                      // Sign Up Button
                      SignUpFormButton(
                        onPressed: () => _handleSignUp(
                          context,
                          _nameController,
                          _emailController,
                          _passwordController,
                          _confirmPasswordController,
                          _phoneController,
                          _ageController,
                          _selectedRole.value,
                          _formKey,
                        ),
                        isLoading: isLoading,
                      ),
                      const SizedBox(height: 16),

                      // Already have account?
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Text(
                            'Already have an account? ',
                            style: TextStyle(
                              color: Colors.grey[600],
                            ),
                          ),
                          TextButton(
                            onPressed: isLoading
                                ? null
                                : () {
                                    // Navigate to login page
                                    Navigator.pushReplacementNamed(
                                      context,
                                      RoutesName.login,
                                    );
                                  },
                            child: Text(
                              'Login',
                              style: TextStyle(
                                color: Theme.of(context).primaryColor,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

